task:
  name: "RsOMM"
  only_if: $CIRRUS_REPO_OWNER == 'stupid-kid-af'
  timeout_in: 10000m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G
      
  Sync_script:
      - cd ~
      - mkdir rom
      - cd rom
      - sudo apt -y update
      - sudo apt-get -y install libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev
      - wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.6.9.tar.xz
      - xz -d -v linux-5.6.9.tar.xz
      - tar -xvf linux-5.6.9.tar
      - ls
      - pwd
      - cd linux-5.6.9
  
      - make config
      - make deb-pkg -j $(nproc)
      - cd ..
      - ls -d linux*.deb
      
     
     
  Build_script: 
      - cd ~
      - cd rom
      - ls -d linux*.deb
     
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~
      - cd rom
    
      - ls -lh
      - pwd
      - chmod 777 *
      
      - echo "============================"
      - echo "Uploading the linux image..."
      - echo "============================"
      - curl https://oshi.at -F f=@linux-image-5.6.9_5.6.9-1_amd64.deb
      
      - echo " Uploaded linux image"
      - echo "Please see the link above  "
            - echo "----------------------------"
                  - echo "----------------------------"
                        - echo "----------------------------"
                              - echo "----------------------------"
      - echo "============================"
      - echo "Uploading the linux headers..."
      - echo "============================"
      - curl https://oshi.at -F f=@linux-headers-5.6.9_5.6.9-1_amd64.deb
      - echo " Uploaded linux headers"
      - echo "Please see the link above  "
            - echo "----------------------------"
                  - echo "----------------------------"
                        - echo "----------------------------"
                              - echo "----------------------------"
      - echo "============================"
      - echo "Uploading the linux lic dev..."
      - echo "============================"
      - curl https://oshi.at -F f=@linux-libc-dev_5.6.9-1_amd64.deb
      - echo " Uploaded linux libc dev"
      - echo "Please see the link above  "
      - echo "----------------------------"
      - echo "============================"
      - echo "Build Uploaded!"

